###################################################################################
#
#
#
###################################################################################

version: '3'
services:

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=128M
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: vrAppBackend
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    volumes:
      - ./mysql_conf:/etc/mysql/conf.d
      - ./mysql_data:/var/lib/mysql

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    env_file:
      - 'env.influxdb'
    volumes:
      # Data persistency
      # sudo mkdir -p /srv/docker/influxdb/data
      - /srv/docker/influxdb/data:/var/lib/influxdb
      
  apache:
    image: 'bitnami/apache:latest'
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - /path/to/app:/app

#  wildfly:
#    build: ./docker-dir
#    container_name: "wildfly"
#    ports:
#      - "8080:8080"
#      - "9990:9990"