-- MySQL Script generated by MySQL Workbench
-- Wed 20 May 2020 05:26:05 PM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vrAppBackend
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vrAppBackend
-- -----------------------------------------------------


CREATE SCHEMA IF NOT EXISTS `vrAppBackend` DEFAULT CHARACTER SET utf8 ;
USE `vrAppBackend` ;


-- -----------------------------------------------------
-- Table `vrAppBackend`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrAppBackend`.`user` (
  `user_id` VARCHAR(45) NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `department` VARCHAR(45) NULL,
  `created_by` VARCHAR(45) NULL,
  `modified_by` VARCHAR(45) NULL,
  `created_time` VARCHAR(45) NULL,
  `modified_time` VARCHAR(45) NULL,
  `role` VARCHAR(15) NULL,
  `is_deleted` TINYINT(1) NULL,
  `course_name` VARCHAR(45) NULL,
  `session` VARCHAR(45) NULL,
  `year` VARCHAR(45) NULL,
  `password_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `fk_user_password_id_idx` (`password_id` ASC),
  CONSTRAINT `fk_user_password_id_idx`
    FOREIGN KEY (`password_id`)
    REFERENCES `vrAppBackend`.`password` (`password_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `vrAppBackend`.`password`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vrAppBackend`.`password` (
  `password_id` VARCHAR(45) NOT NULL,
  `password_hash` VARCHAR(60) NULL,
  PRIMARY KEY (`password_id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;